apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: cloudon
  name: mongodb-pv-claim
  labels:
    app: cloudon
spec:
  storageClassName: local-mongodb-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi