apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: yogiyo
  name: redis-pv
spec:
  storageClassName: redis-sc
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/redis/