apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: yogiyo
  name: postgres-pvc
  labels:
    app: yogiyo
spec:
  storageClassName: postgres-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi