apiVersion: v1
kind: ConfigMap
metadata:
  namespace: yogiyo
  name: yogiyo-config
data:
  POSTGRES_DB: postgres_db
  POSTGRES_HOST: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_USER: yogiyo
  POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
  REDIS_DB: "0"
  REDIS_HOST: redis
  REDIS_PASSWORD: redis
  REDIS_PORT: "6379"
  REST_API_VERSION: v1
  REST_API_HOST: backend.yogiyo-dev.com
  REST_API_PORT: "80"
  DJANGO_DEBUG: "True"
  DJANGO_LOG_PATH: /var/log/containers
  DJANGO_LOG_LEVEL: DEBUG