apiVersion: skaffold/v2beta3
kind: Config
build:
  artifacts:
    - context: src
      image: backend
      docker:
        dockerfile: ./backend/Dockerfile
    - context: src
      image: frontend
      docker:
        dockerfile: ./frontend/Dockerfile
# only effective when "--port-forward" option is given
portForward:
 - resourceType: service
   resourceName: redis
   namespace: yogiyo
   port: 6379
   localPort: 6379
 - resourceType: service
   resourceName: postgres
   namespace: yogiyo
   port: 5432
   localPort: 5432
profiles:
  - name: dev-profile
    # automatically activate this profile when current context is "minikube"
    activation:
      - kubeContext: minikube
        command: dev
    build:
      tagPolicy:
        #dateTime: {}
        sha256: {}
      local:
        push: false
        #useDockerCLI: true
    deploy:
      # This overrides the progressDeadlineSeconds in every deployment.yaml file
      statusCheckDeadlineSeconds: 2000
      kubectl:
        # Currently not necessary as progressDeadlineSeconds is specified in deployment.yaml
        # flags:
        #   apply:
        #     - "--timeout=1000s"
        manifests:
          - kubernetes-manifests/local/0/**.yaml
          - kubernetes-manifests/local/1/**.yaml
          - kubernetes-manifests/local/2/**.yaml
          - kubernetes-manifests/local/3/**.yaml