apiVersion: skaffold/v2beta3
kind: Config
build:
  artifacts:
    - context: src
      image: backend
      docker:
        dockerfile: ./backend/Dockerfile
    - context: src
      image: frontend
      docker:
        dockerfile: ./frontend/Dockerfile
# all services are exposed by default in "skaffold dev" mode so below configuration is not needed.
# portForward:
#  - resourceType: service
#    resourceName: redis
#    namespace: yogiyo
#    port: 6379
#    localPort: 6379
profiles:
  - name: dev-profile
    # automatically activate this profile when current context is "minikube"
    activation:
      - kubeContext: minikube
        command: dev
    build:
      tagPolicy:
        #dateTime: {}
        #sha256: {}
        # tag images as "dev" in order to save disk space
        envTemplate:
          template: "{{.IMAGE_TAG_FOR_DEV}}"
      local:
        push: false
        #useDockerCLI: true
    deploy:
      # This overrides the progressDeadlineSeconds in every deployment.yaml file
      statusCheckDeadlineSeconds: 2000
      kubectl:
        # flags:
        #   apply:
        #     - "--v=7"
        manifests:
          - kubernetes-manifests/local/0/**.yaml
          - kubernetes-manifests/local/1/**.yaml
          - kubernetes-manifests/local/2/**.yaml
          - kubernetes-manifests/local/3/**.yaml