apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: yogiyo
  name: redis-pvc
  labels:
    app: yogiyo
spec:
  storageClassName: redis-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi