apiVersion: v1
kind: ConfigMap
metadata:
  namespace: yogiyo
  name: yogiyo-config
data:
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
  POSTGRES_DB: yogiyo_db
  POSTGRES_USER: yogiyo
  POSTGRES_PASSWORD: yogiyo1234
  POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
  REDIS_DB: "0"
  REDIS_HOST: redis
  REDIS_PASSWORD: yogiyo1234
  REDIS_PORT: "6379"
  BACKEND_VERSION: v1
  BACKEND_HOST: backend.yogiyo-dev.com
  BACKEND_PORT: "80"
  DJANGO_DEBUG: "False"
  DJANGO_ALLOWED_HOSTS: backend.yogiyo-dev.com
  DJANGO_LOG_PATH: /var/log/containers
  DJANGO_LOG_LEVEL: DEBUG