apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler 
metadata: 
  namespace: cloudon
  name: rest-api 
spec: 
  maxReplicas: 10 
  minReplicas: 2 
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: rest-api
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60