apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata: 
  namespace: yogiyo
  name: frontend 
spec: 
  maxReplicas: 2 
  minReplicas: 2 
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: frontend
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60