apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  namespace: yogiyo
  name: yogiyo-ingress
  annotations:
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "ingress-route"
    nginx.ingress.kubernetes.io/session-cookie-expires: "172800"
    nginx.ingress.kubernetes.io/session-cookie-max-age: "172800"
spec:
  rules:
  - host: yogiyo-local.com
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 8080
  - host: admin.yogiyo-local.com
    http:
      paths:
      - path: /
        backend:
          serviceName: frontend
          servicePort: 8081
  - host: backend.yogiyo-local.com
    http:
      paths:
      - path: /
        backend:
          serviceName: backend
          servicePort: 8000