apiVersion: batch/v1
kind: Job
metadata:
  namespace: cloudon
  name: cloudon-mongodb-init
spec:
  template:
    metadata:
      name: cloudon-mongodb-init
    spec:
      initContainers:
      - name: check-ddb-ready
        image: mongo
        command: ["/bin/sh", "-c", 
          "until mongo --host $(MONGO_HOST):$(MONGO_PORT) --eval 'db.adminCommand(\"ping\")'; 
          do echo waiting for database; sleep 2; done;"]
        envFrom:
          - configMapRef:
              name: cloudon-config
      containers:
      - name: cloudon-mongodb-init
        image: mongo
        command: [ "/bin/sh", "-c", "mongo --host $(MONGO_HOST):$(MONGO_PORT) $(MONGO_DATABASE) ",
        " -u $(MONGO_USERNAME)",
        " -p $(MONGO_PASSWORD)",
        " --authenticationDatabase admin ",
        " --eval \"db.createUser({user: '$(MONGO_USERNAME)', pwd: '$(MONGO_USERNAME)', roles:[{role:'dbOwner', db: '$(MONGO_DATABASE)'}]});\"" ]
        envFrom:
          - configMapRef:
              name: cloudon-config
      restartPolicy: OnFailure