apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cloudon
  name: ddb
spec:
  progressDeadlineSeconds: 1000
  replicas: 1
  selector:
    matchLabels:
      app: ddb
      tier: db
  template:
    metadata:
      labels:
        app: ddb
        tier: db
    spec:
      restartPolicy: Always
      containers:
        - image: mongo:3.6
          imagePullPolicy: "IfNotPresent"
          name: mongo
          ports:
            - containerPort: 27017
          livenessProbe:
            exec:
              command:
                - mongo
                - --eval
                - db.adminCommand('ping')
            failureThreshold: 6
            initialDelaySeconds: 360
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          envFrom:
            - configMapRef:
                name: cloudon-config
          env:
            - name: MONGO_INITDB_DATABASE
              value: $(MONGO_DATABASE)
            - name: MONGO_INITDB_ROOT_USERNAME
              value: $(MONGO_USERNAME)
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: $(MONGO_PASSWORD)
          volumeMounts:
            - mountPath: /data/db
              name: mongodb-storage
          resources:
              requests:
                cpu: "500m"
                memory: "256Mi"
              limits:
                cpu: "1000m"
                memory: "1Gi"
      volumes:
        - name: mongodb-storage
          persistentVolumeClaim:
            claimName: mongodb-pv-claim
