apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cloudon
  name: data-crawler
  labels:
    app: data-crawler
    tier: backend
spec:
  progressDeadlineSeconds: 1000
  replicas: 1
  selector:
    matchLabels:
      app: data-crawler
      tier: backend
  template:
    metadata:
      labels:
        app: data-crawler
        tier: backend
    spec:
      restartPolicy: Always
      initContainers:
      - name: check-ddb-ready
        image: mongo
        command: ["/bin/sh", "-c", 
          "until mongo --host $(MONGO_HOST):$(MONGO_PORT) --eval 'db.adminCommand(\"ping\")'; 
          do echo waiting for database; sleep 2; done;"]
        envFrom:
          - configMapRef:
              name: cloudon-config
      - name: check-rdb-ready
        image: postgres
        command: ['sh', '-c', 
          'until pg_isready -h $(POSTGRES_HOST) -p $(POSTGRES_PORT); 
          do echo waiting for database; sleep 2; done;']
        envFrom:
          - configMapRef:
              name: cloudon-config
      containers:
      - name: data-crawler
        image: data_crawler
        envFrom:
          - configMapRef:
              name: cloudon-config
        resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
