apiVersion: v1
kind: Service
metadata:
  namespace: cloudon
  name: frontend
  labels:
    app: frontend
    tier: frontend
spec:
  type: LoadBalancer
  # for sticky session
  sessionAffinity: ClientIP
  externalTrafficPolicy: Local
  ports:
    - name: customer
      port: 8080
      targetPort: 8080
    - name: admin
      port: 8081
      targetPort: 8081
  selector:
    app: frontend
    tier: frontend
