apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: yogiyo
  name: frontend
  labels:
    app: frontend
    tier: frontend
spec:
  progressDeadlineSeconds: 1000
  selector:
    matchLabels:
      app: frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      restartPolicy: Always
      containers:
      - name: frontend
        image: frontend
        command: [  "/bin/sh", "-c", "/app/docker-entrypoint.sh" ]
        envFrom:
          - configMapRef:
              name: yogiyo-config
        ports:
        - name: web-server
          containerPort: 8080
        resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
