apiVersion: v1
kind: Service
metadata:
  namespace: yogiyo
  name: postgres
  labels:
    app: yogiyo
    tier: db
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    app: postgres
