# This file creates a job that migrates the Postgres database. The job creates a
# pod from the specified Docker image, wait for the database to get ready, and
# run database migration once the Postgres database service is ready to receive
# connections.
apiVersion: batch/v1
kind: Job
metadata:
  namespace: yogiyo
  name: yogiyo-backend-entrypoint
spec:
  template:
    metadata:
      name: yogiyo-backend-entrypoint
    spec:
      initContainers:
      - name: check-postgres-ready
        image: postgres
        command: ['sh', '-c', 
          'until pg_isready -h $(POSTGRES_HOST) -p $(POSTGRES_PORT); 
          do echo waiting for database; sleep 2; done;']
        envFrom:
          - configMapRef:
              name: yogiyo-config
      containers:
      - name: yogiyo-backend-entrypoint
        image: backend
        command: [  "/bin/sh", "-c", "/backend/docker-entrypoint.sh" ]
        envFrom:
          - configMapRef:
              name: yogiyo-config
      restartPolicy: OnFailure