apiVersion: v1
kind: Service
metadata:
  namespace: yogiyo
  name: backend
  labels:
    app: yogiyo
    tier: backend
spec:
  type: LoadBalancer
  # for sticky session
  sessionAffinity: ClientIP
  externalTrafficPolicy: Local
  ports:
    - name: django-gunicorn
      port: 8001
      targetPort: 8001
    - name: nginx
      port: 8000
      targetPort: 8000
  selector:
    app: backend
    tier: backend
