apiVersion: v1
kind: Service
metadata:
  namespace: yogiyo
  name: redis
  labels:
    app: yogiyo
    tier: db
spec:
  type: NodePort
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    app: redis
