apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: yogiyo
  name: frontend
  labels:
    app: frontend
    tier: frontend
spec:
  progressDeadlineSeconds: 1000
  selector:
    matchLabels:
      app: frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: frontend
        tier: frontend
    spec:
      restartPolicy: Always
      #initContainers:
      # Wait for the backend Rest API
      # - name: check-backend-ready
      #   image: redis
      #   command: ['sh', '-c', 
      #     'until redis-cli -h $(REDIS_HOST) -p $(REDIS_PORT) ping; 
      #     do echo waiting for database; sleep 2; done;']
      #   envFrom:
      #     - configMapRef:
      #         name: yogiyo-config
      containers:
      - name: frontend
        image: frontend
        command: [  "/bin/sh", "-c", "/app/docker-entrypoint.sh" ]
        env:
          # setting below to specify pod name in application log
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        envFrom:
          - configMapRef:
              name: yogiyo-config
        ports:
        - name: web-server
          containerPort: 8080
        resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
