apiVersion: v1
kind: Service
metadata:
  namespace: yogiyo
  name: frontend
  annotations:
    # This annotation is only required if you are creating an internal facing ELB. Remove this annotation to create public facing ELB.
    #service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
  labels:
    app: frontend
    tier: frontend
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 8080
      targetPort: 8080
  selector:
    app: frontend
    tier: frontend
