apiVersion: v1
kind: Service
metadata:
  namespace: yogiyo
  name: redis
  annotations:
    # This annotation is only required if you are creating an internal facing ELB. Remove this annotation to create public facing ELB.
    #service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
  labels:
    app: yogiyo
    tier: db
spec:
  type: NodePort
  ports:
    - port: 6379
  selector:
    app: redis
