apiVersion: v1
kind: Service
metadata:
  namespace: yogiyo
  name: frontend
  labels:
    app: frontend
    tier: frontend
spec:
  type: LoadBalancer
  # for sticky session
  sessionAffinity: ClientIP
  externalTrafficPolicy: Local
  ports:
    - name: web
      port: 8080
      targetPort: 8080
  selector:
    app: frontend
    tier: frontend
