# Generated by Django 3.2 on 2021-04-30 08:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forum', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='discussion',
            unique_together={('user_id', 'forum_id', 'discussion_id')},
        ),
        migrations.AlterUniqueTogether(
            name='forum',
            unique_together={('user_id', 'forum_id')},
        ),
    ]
