#######################################################################
#
# Currently not working due to minikube v1.19.0 bug.
# See below for more information:
# https://stackoverflow.com/questions/67061272/kubernetes-ingress-internal-error-occurred-failed-calling-webhook-validate-ng
#
#######################################################################
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: yogiyo
  name: yogiyo-ingress
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/ip-address-type: dualstack
    kubernetes.io/ingress.class: alb
    # alb.ingress.kubernetes.io/target-type: ip
    # alb.ingress.kubernetes.io/subnets: subnet-03cb2be8777e74290, subnet-087e2a227288f7028, subnet-08dbc1142b67a3934
    # alb.ingress.kubernetes.io/tags: Environment=prod,Team=Prod
    # alb.ingress.kubernetes.io/target-group-attributes: stickiness.enabled=true,stickiness.lb_cookie.duration_seconds=60
spec:
  rules:
    - host: yogiyo-nuno.click
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 8080
    - host: frontend.yogiyo-nuno.click
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 8080
    - host: backend.yogiyo-nuno.click
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8001
